version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      CONNECTION_URL: jdbc:mysql://db:3306/university?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: university
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: